cp -r single_domain SQuAD_small
cp -r single_domain NewsQA_small
cp -r single_domain HotpotQA_small
cp -r single_domain NaturalQuestions_small
cp -r single_domain TriviaQA_small
cp -r checkpoints/SQuAD/step_best/ SQuAD_small/squad/checkpoints/
cp -r checkpoints/NewsQA/step_best/ NewsQA_small/squad/checkpoints/
cp -r checkpoints/HotpotQA/step_best/ HotpotQA_small/squad/checkpoints/
cp -r checkpoints/NaturalQuestions/step_best/ NaturalQuestions_small/squad/checkpoints/
cp -r checkpoints/TriviaQA/step_best/ TriviaQA_small/squad/checkpoints/
